azure_rm_virtualmachine:
  resource_group: Testing
  name: testvm10
  vm_size: Standard_D1
  admin_username: chouseknecht
  admin_password: Password!
  image:
    offer: CentOS
    publisher: OpenLogic
    sku: '7.1'
    version: latest
